<?php

// Shelter Info Form Fields
$fields = [
    [
        'id' => 'FnehdShelterAjaxAction',
		"title" => __('Ajax Action', 'fnehousing'),
        'name' => 'action',
        'type' => 'hidden',
        'placeholder' => '',
        'div-class' => 'col-md-6',
        'callback' => 'fnehd_insert_shelter',
        'display' => false,
        'help-info' => '',
        'required' => false,
    ],
    [
        'id' => 'FnehdShelterAjaxNonce',
		"title" => __('Ajax Nonce', 'fnehousing'),
        'name' => 'nonce',
        'type' => 'hidden',
        'placeholder' => '',
        'div-class' => 'col-md-6',	
        'callback' => wp_create_nonce('fnehd_shelter_nonce'),
        'display' => false,
        'help-info' => '',
        'required' => false,
    ],
    [
        'id' => 'FnehdShelterID',
		"title" => __('Shelter ID', 'fnehousing'),
        'name' => 'shelter_id',
        'type' => 'hidden',
        'placeholder' => '',
        'div-class' => 'col-md-6',
        'callback' => '',
        'display' => false,
        'help-info' => '',
        'required' => false,
    ],
	[
        'id' => 'FnehdShelterRefID',
		"title" => __('Ref ID', 'fnehousing'),
        'name' => 'ref_id',
        'type' => 'hidden',
        'placeholder' => '',
        'div-class' => 'col-md-6',
        'callback' => '',
        'display' => false,
        'help-info' => '',
        'required' => false,
    ],
	[
        'id' => 'FnehdShelterUserID',
		"title" => __('User ID', 'fnehousing'),
        'name' => 'user_id',
        'type' => 'hidden',
        'placeholder' => '',
        'div-class' => 'col-md-6',
        'callback' => '',
        'display' => false,
        'help-info' => '',
        'required' => false,
    ],
    [
        "id" => "FnehdShelterName",
        "title" => __('Shelter Name', 'fnehousing'),
        "name" => "shelter_name",
        "type" => "text",
        "placeholder" => "",
        "div-class" => "col-md-6",
        "callback" => "",
        "display" => true,
        "help-info" => "",
        "required" => true,
    ],
    [
        "id" => "FnehdShelterOrganization",
        "title" => __('Shelter Organization', 'fnehousing'),
        "name" => "shelter_organization",
        "type" => "text",
        "placeholder" => "",
        "div-class" => "col-md-6",
        "callback" => "",
        "display" => true,
        "help-info" => "",
        "required" => true,
    ],
    [
        "id" => "FnehdShelterEmail",
        "title" => __('Email', 'fnehousing'),
        "name" => "email",
        "type" => "text",
        "placeholder" => "",
        "div-class" => "col-md-6",
        "callback" => "",
        "display" => true,
        "help-info" => "",
        "required" => true,
    ],
    [
        "id" => "FnehdShelterPhone",
        "title" => __('Phone', 'fnehousing'),
        "name" => "phone",
        "type" => "text",
        "placeholder" => "",
        "div-class" => "col-md-6",
        "callback" => "",
        "display" => true,
        "help-info" => "",
        "required" => true,
    ],
    [
        "id" => "FnehdShelterAddress",
        "title" => __('Address', 'fnehousing'),
        "name" => "address",
        "type" => "text",
        "placeholder" => "",
        "div-class" => "col-md-12",
        "callback" => "",
        "display" => true,
        "help-info" => "",
        "required" => true,
    ],
    [
        "id" => "FnehdShelterManager",
        "title" => __('Manager', 'fnehousing'),
        "name" => "manager",
        "type" => "text",
        "placeholder" => "",
        "div-class" => "col-md-6",
        "callback" => "",
        "display" => true,
        "help-info" => "",
        "required" => true,
    ],
    [
        "id" => "FnehdShelterProjectType",
        "title" => __('Project Type', 'fnehousing'),
        "name" => "project_type",
        "type" => "select",
        "placeholder" => "",
        "div-class" => "col-md-6",
        "callback" => "",
        "display" => true,
        "help-info" => "",
        "required" => true,
    ],
    [
        "id" => "FnehdShelterDescription",
        "title" => __('Description', 'fnehousing'),
        "name" => "description",
        "type" => "textarea",
        "placeholder" => "",
        "div-class" => "col-md-12",
        "callback" => "",
        "display" => true,
        "help-info" => "",
        "required" => true,
    ],
    [
        "id" => "FnehdShelterMainImage",
        "title" => __('Main Shelter Image', 'fnehousing'),
        "name" => "main_image",
        "type" => "image",
        "placeholder" => "",
        "div-class" => "col-md-2",
        "callback" => "",
        "display" => true,
        "help-info" => "",
        "required" => true,
    ],
    [
        "id" => "FnehdShelterGallery",
        "title" => __('Gallery', 'fnehousing'),
        "name" => "gallery",
        "type" => "gallery",
        "placeholder" => "",
        "div-class" => "col-md-2",
        "callback" => "",
        "display" => true,
        "help-info" => "",
        "required" => true,
    ]

];

if($form_type == "edit"){ //update ajax action field
	$fields[0]['callback'] = 'fnehd_update_shelter'; 
	$fields[1]['callback'] = wp_create_nonce('fnehd_shelter_update_nonce'); //update nonce for edit form
	$fields[1]['name'] = 'update_nonce'; 
}
include FNEHD_PLUGIN_PATH . "templates/forms/form-fields/form-fields-manager.php";
