<?php
// Generate nonce values
$create_nonce = wp_create_nonce('fnehd_shelter_nonce');
$update_nonce = wp_create_nonce('fnehd_shelter_update_nonce');


// Shelter Info Form Fields
$fields = [
    [
        'id' => 'FnehdShelterAjaxAction',
		"title" => __('Ajax Action', 'fnehousing'),
        'name' => 'action',
        'type' => 'hidden',
        'placeholder' => '',
        'div-class' => 'col-md-6',
        'callback' => 'fnehd_insert_shelter',
        'display' => false,
        'help-info' => '',
        'required' => false,
    ],
    [
        'id' => 'FnehdShelterAjaxNonce',
		"title" => __('Ajax Nonce', 'fnehousing'),
        'name' => 'nonce',
        'type' => 'hidden',
        'placeholder' => '',
        'div-class' => 'col-md-6',	
        'callback' => $create_nonce,
        'display' => false,
        'help-info' => '',
        'required' => false,
    ],
    [
        'id' => 'FnehdShelterID',
		"title" => __('Shelter ID', 'fnehousing'),
        'name' => 'shelter_id',
        'type' => 'hidden',
        'placeholder' => '',
        'div-class' => 'col-md-6',
        'callback' => '',
        'display' => false,
        'help-info' => '',
        'required' => false,
    ],
	[
        'id' => 'FnehdShelterRefID',
		"title" => __('Ref ID', 'fnehousing'),
        'name' => 'ref_id',
        'type' => 'hidden',
        'placeholder' => '',
        'div-class' => 'col-md-6',
        'callback' => '',
        'display' => false,
        'help-info' => '',
        'required' => false,
    ],
	[
        'id' => 'FnehdShelterUserID',
		"title" => __('User ID', 'fnehousing'),
        'name' => 'user_id',
        'type' => 'hidden',
        'placeholder' => '',
        'div-class' => 'col-md-6',
        'callback' => '',
        'display' => false,
        'help-info' => '',
        'required' => false,
    ],
    [
        "id" => "FnehdShelterName",
        "title" => __('Shelter Name', 'fnehousing'),
        "name" => "shelter_name",
        "type" => "text",
        "placeholder" => "",
        "div-class" => "col-md-6",
        "callback" => "",
        "display" => true,
        "help-info" => "",
        "required" => true,
    ],
    [
        "id" => "FnehdShelterOrganization",
        "title" => __('Shelter Organization', 'fnehousing'),
        "name" => "shelter_organization",
        "type" => "text",
        "placeholder" => "",
        "div-class" => "col-md-6",
        "callback" => "",
        "display" => true,
        "help-info" => "",
        "required" => true,
    ],
    [
        "id" => "FnehdShelterEmail",
        "title" => __('Email', 'fnehousing'),
        "name" => "email",
        "type" => "text",
        "placeholder" => "",
        "div-class" => "col-md-6",
        "callback" => "",
        "display" => true,
        "help-info" => "",
        "required" => true,
    ],
    [
        "id" => "FnehdShelterPhone",
        "title" => __('Phone', 'fnehousing'),
        "name" => "phone",
        "type" => "text",
        "placeholder" => "",
        "div-class" => "col-md-6",
        "callback" => "",
        "display" => true,
        "help-info" => "",
        "required" => true,
    ],
	[
        "id" => "FnehdShelterFax",
        "title" => __('Fax', 'fnehousing'),
        "name" => "fax",
        "type" => "text",
        "placeholder" => "",
        "div-class" => "col-md-6",
        "callback" => "",
        "display" => true,
        "help-info" => "",
        "required" => true,
    ],
	[
        "id" => "FnehdShelterWebsite",
        "title" => __('Website', 'fnehousing'),
        "name" => "website",
        "type" => "text",
        "placeholder" => "",
        "div-class" => "col-md-6",
        "callback" => "",
        "display" => true,
        "help-info" => "",
        "required" => true,
    ],
    [
        "id" => "FnehdShelterAddress",
        "title" => __('Address', 'fnehousing'),
        "name" => "address",
        "type" => "text",
        "placeholder" => "",
        "div-class" => "col-md-12",
        "callback" => "",
        "display" => true,
        "help-info" => "",
        "required" => true,
    ],
    [
        "id" => "FnehdShelterManager",
        "title" => __('Manager', 'fnehousing'),
        "name" => "manager",
        "type" => "text",
        "placeholder" => "",
        "div-class" => "col-md-6",
        "callback" => "",
        "display" => true,
        "help-info" => "",
        "required" => true,
    ],
    [
        "id" => "FnehdShelterProjectType",
        "title" => __('Project Type', 'fnehousing'),
        "name" => "project_type",
        "type" => "select",
        "placeholder" => "",
        "div-class" => "col-md-6",
        "callback" => [
						"ES: Emergency Shelter (Entry/Exit)",
						"RRH: Rapid Re-Housing (Housing With Or Without Services)",
						"TH: Transitional Housing",
						"PSH: Permanent Supportive Housing",
						"ES: Emergency Shelter (Night-By-Night)",
						"OPH: Other Permanent Housing (No Services)"
					],
        "display" => true,
        "help-info" => "",
        "required" => true,
    ],
    [
        "id" => "FnehdShelterDescription",
        "title" => __('Description', 'fnehousing'),
        "name" => "description",
        "type" => "textarea",
        "placeholder" => "",
        "div-class" => "col-md-12",
        "callback" => "",
        "display" => true,
        "help-info" => "",
        "required" => true,
    ],
    [
        "id" => "FnehdShelterMainImage",
        "title" => __('Main Shelter Image', 'fnehousing'),
        "name" => "main_image",
        "type" => "image",
        "placeholder" => "",
        "div-class" => "col-md-2",
        "callback" => "",
        "display" => true,
        "help-info" => "",
        "required" => true,
    ],
    [
        "id" => "FnehdShelterGallery",
        "title" => __('Gallery', 'fnehousing'),
        "name" => "gallery",
        "type" => "gallery",
        "placeholder" => "",
        "div-class" => "col-md-8",
        "callback" => "",
        "display" => true,
        "help-info" => "",
        "required" => true,
    ]

];

if ($form_type === "edit") { 
    $fields[0]['callback'] = 'fnehd_update_shelter'; // Change action for update
    $fields[1]['callback'] = $update_nonce; // Use update nonce
    $fields[1]['name'] = 'update_nonce'; // Ensure correct nonce field name
}
include FNEHD_PLUGIN_PATH . "templates/forms/form-fields/form-fields-manager.php";
