<?php
	
	
//Shelter Info Form Fields
 $fields = [
  
	[
	  "id" => "fnehd_eligible_individuals",
	  "title" => __('Eligible Individuals', 'fnehousing') ,
	  "name" => "eligible_individuals[]",
	  "type" => "multi_select",
	  "placeholder" => "",
	  "div-class" => "col-md-6",
	  "callback" => ['women', 'men', 'families', 'transgender'],
	  "display" => true,
	  "help-info" => "",
	  "required" => true,
	],
	[
	  "id" => "fnehd_accepted_ages",
	  "title" => __('Accepted Ages', 'fnehousing') ,
	  "name" => "accepted_ages[]",
	  "type" => "multi_select",
	  "placeholder" => "",
	  "div-class" => "col-md-6"	,
	  "callback" => ['Youth(below 18)', 'Adults(18-69)', 'Older Adults(70+)'],
	  "display" => true,
	  "help-info" => "",
	  "required" => true,
	],
	[
	  "id" => "fnehd_specific_services",
	  "title" => __('Accepts clients that…', 'fnehousing') ,
	  "name" => "specific_services[]",
	  "type" => "multi_select",
	  "placeholder" => "",
	  "div-class" => "col-md-12",
	  "callback" =>  ['Require oxygen', 'Cannot independently perform tasks', 'Need dressing assistance', 'Need toileting assistance', 'Need transferring assistance', 'Need grooming assistance', 'Need eating assistance', 'Need support with their medication', 'Need cooking or grocery assistance', 'Need laundry assistance', 'Need transportation assistance', 'Need support with appointments'],
	  "display" => true,
	  "help-info" => "",
	  "required" => true,
	],
    [
	  "id" => "fnehd_pet_policy",
	  "title" => __('Pet policy', 'fnehousing') ,
	  "name" => "pet_policy",
	  "type" => "select",
	  "placeholder" => "",
	  "div-class" => "col-md-3",
	  "callback" => ['Allowed', 'Not allowed'],
	  "display" => true,
	  "help-info" => "",
	  "required" => true,
	],	
	[
	  "id" => "fnehd_shelter_availabity",
	  "title" => __('Availability', 'fnehousing') ,
	  "name" => "availability",
	  "type" => "select",
	  "placeholder" => "",
	  "div-class" => "col-md-3",
	  "callback" => ['Available', 'Unavailable'],
	  "display" => true,
	  "help-info" => "",
	  "required" => true,
	],
	[
	  "id" => "fnehd_bed_capacity",
	  "title" => __('Bed Capacity', 'fnehousing') ,
	  "name" => "bed_capacity",
	  "type" => "number",
	  "placeholder" => "",
	  "div-class" => "col-md-3",
	  "callback" => "",
	  "display" => true,
	  "help-info" => "",
	  "required" => true,
	],			
	[
	  "id" => "fnehd_available_bed",
	  "title" => __('Available Beds', 'fnehousing') ,
	  "name" => "available_beds",
	  "type" => "number",
	  "placeholder" => "",
	  "div-class" => "col-md-3",
	  "callback" => "",
	  "display" => true,
	  "help-info" => "",
	  "required" => true,
	],
	
	
];

include FNEHD_PLUGIN_PATH."templates/forms/form-fields/form-fields-manager.php";